# Target Minecraft & Fabric environment
minecraft_version=26.1.1
loader_version=0.19.5
fabric_version=0.145.3+26.1.1

# Mod properties
mod_version=1.0.0
maven_group=ruinerpie.pancreas
archives_base_name=Pancreas

# Java Toolchain
java_version=25

# Gradle performance
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false
